[project]
name = "nixos"
revision = "1.0"

[defaults]
provider = "bw"

[profiles.default]

# Personal Access Tokens
GITHUB_PAT = { description = "GitHub Personal Access Token", ref = { item = "GitHub Personal Access Token" } }
ACCESS_TOKENS_STRING = { description = "String of combined PATs used by Nix", composed = "access-tokens = github.com=${GITHUB_PAT}" }

# API Keys
API_KEYS__STEAMGRIDDB = { description = "SteamGridDB API Key", ref = { item = "SteamGridDB API Key" } }

# Private SSH Keys
PRIVATE_KEYS__PROXMOX_NIX_VM__SRAVAN = { description = "Private key for proxmox-nix-vm sravan", ref = { item = "Proxmox NixOS VM SSH Key", field = "privateKey" } }
PRIVATE_KEYS__ORYP7__SRAVAN = { description = "Private key for oryp7 sravan", ref = { item = "System76 Oryx Pro 7 SSH Key", field = "privateKey" } }
PRIVATE_KEYS__POWERSPEC__SRAVAN = { description = "Private key for powerspec sravan", ref = { item = "Powerspec SSH Key", field = "privateKey" } }

# User Passwords
PASSWORDS__PROXMOX_NIX_VM__SRAVAN = { description = "Password for proxmox-nix-vm sravan", ref = { item = "Proxmox NixOS VM" } }
PASSWORDS__ORYP7__SRAVAN = { description = "Password for oryp7 sravan", ref = { item = "Oryx Pro 7 Laptop" } }
PASSWORDS__POWERSPEC__SRAVAN = { description = "Password for powerspec sravan", ref = { item = "Powerspec Desktop" } }

# Home VPN WireGuard
HOME_VPN_WIREGUARD__ORYP7__FULL_TUNNEL = { description = "WireGuard full tunnel config/key for oryp7", ref = { item = "Home VPN Wireguard Oryx Pro 7 Full Tunnel" } }
HOME_VPN_WIREGUARD__ORYP7__SPLIT_TUNNEL = { description = "WireGuard split tunnel config/key for oryp7", ref = { item = "Home VPN Wireguard Oryx Pro 7 Split Tunnel" } }

# Proton VPN WireGuard
PROTON_VPN_WIREGUARD__JP_FREE_20 = { description = "Proton VPN WireGuard key for jp-free-20", ref = { item = "Proton VPN Wireguard JP Free 20" } }

# Syncthing
SYNCTHING__GUI_PASSWORD = { description = "Syncthing GUI Password", ref = { item = "Syncthing GUI" } }
SYNCTHING__DEVICES__ORYP7__CERT = { description = "Syncthing cert for oryp7", ref = { item = "Syncthing Oryx Pro 7 Cert" } }
SYNCTHING__DEVICES__ORYP7__KEY = { description = "Syncthing key for oryp7", ref = { item = "Syncthing Oryx Pro 7 Key" } }
SYNCTHING__DEVICES__POWERSPEC__CERT = { description = "Syncthing cert for powerspec", ref = { item = "Syncthing Powerspec Cert" } }
SYNCTHING__DEVICES__POWERSPEC__KEY = { description = "Syncthing key for powerspec", ref = { item = "Syncthing Powerspec Key" } }

# Samba Clients
SAMBA_CLIENT__FILESERVER__USERNAME = { description = "Samba client username for fileserver", ref = { item = "Fileserver - Samba User", field = "username" } }
SAMBA_CLIENT__FILESERVER__PASSWORD = { description = "Samba client password for fileserver", ref = { item = "Fileserver - Samba User", field = "password" } }
SAMBA_CLIENT__FILESERVER = { description = "Samba client credentials for fileserver", composed = "username=${SAMBA_CLIENT__FILESERVER__USERNAME}\npassword=${SAMBA_CLIENT__FILESERVER__PASSWORD}" }

SAMBA_CLIENT__MEDIASERVER__USERNAME = { description = "Samba client username for mediaserver", ref = { item = "Media Server - Samba User", field = "username" } }
SAMBA_CLIENT__MEDIASERVER__PASSWORD = { description = "Samba client password for mediaserver", ref = { item = "Media Server - Samba User", field = "password" } }
SAMBA_CLIENT__MEDIASERVER = { description = "Samba client credentials for mediaserver", composed = "username=${SAMBA_CLIENT__MEDIASERVER__USERNAME}\npassword=${SAMBA_CLIENT__MEDIASERVER__PASSWORD}" }
